baseurl: /
title: mwgnd.
theme: hugo-PaperModX
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$


enableRobotsTXT: true
enableEmoji: true

params:
  DateFormat: "January 2, 2006"
  mainSections:
    - post
  
  comments: true

  # theme params
  DisableLanguageSwitch: true
  defaultTheme: auto
  ShowToc: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: true
  EnableImageZoom: true
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  Email: lsy@mailbox.org

  socialIcons:
    - name: github-simple
      url: "https://github.com/mwgnd"
    - name: telegram-simple
      url: "https://t.me/qwertzx"
    - name: rss-simple
      url: "feed.xml"
    - name: email
      url: email
    

  homeInfoParams:
    Title: "are blogs still a thing in 2024?"
    Content: >
      This is just a personal blog of mine to share my journey in learning R,
      where i a am going to post my code snippets, documentation and other R related stuff.
      I studied social sciences with a focus on computational social science and data analysis. 
      I have been using R for quite a while now and I am still learning new things every day 
      like building this blog with [**blogdown**](https://bookdown.org/yihui/blogdown/).
      I hope you will find this blog helpful.


outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
   main:
      - name: About
        url: /about/
        weight: 1
      - name: Tags
        url: /tags/
        weight: 2
      - name: Archive
        url: /archives/
        weight: 3


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
